version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: rick_morty_postgres
    environment:
      POSTGRES_DB: rick_morty_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d rick_morty_app"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - rick_morty_network

  redis:
    image: redis:7-alpine
    container_name: rick_morty_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - rick_morty_network

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  rick_morty_network:
    driver: bridge
